name: Release

on:
  workflow_dispatch:
    
  push:
    branches:
      - 'main'

jobs:
  admin-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get Current Date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          #registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          labels: |
            "Maintainer: <Paper-Dragon 2678885646@qq.com>"
          tags: |
            jockerdragon/ifconfig.icu:${{ github.sha }}
            jockerdragon/ifconfig.icu:${{ steps.date.outputs.today }}
            jockerdragon/ifconfig.icu:latest