[package]
name = "ifconfig_dot_icu"
version = "0.1.1"
edition = "2023"
authors = ["PaperDragon <2678885646@qq.com> && Khanh Ngo <k@ndk.name>"]

[dependencies]
actix-web = "3"
actix-files = "0.5.0"
tera = "1"
serde = "1"
serde_json = "1"
maxminddb = "0.17"
env_logger = "0.5"
regex = "1"
